name = "freqscan"
version = "0.1.1"
target = "javascript"

description = "A radio frequency name generator project"
licences = ["CC-BY-NC-SA-4.0"]
repository = { type = "github", user = "just-maiyak", repo = "freqscan" }
links = [{ title = "Website", href = "https://freqscan.yefimch.uk" }]

[dependencies]
lustre = ">= 5.2.1 and < 6.0.0"
gleam_stdlib = ">= 0.60.0 and < 1.0.0"
rsvp = ">= 1.1.2 and < 2.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.5.1 and < 2.0.0"
lustre_dev_tools = ">= 1.9.0 and < 2.0.0"
